install_as_dev:
	@sudo pip install . --break-system-packages


install_global:
	@git clone https://github.com/vgomes-p/managit.git ~/.managit
	@sudo pip install ~/.managit/program/. --break-system-packages
	@echo "managit installed at ~/.managit, now you can call is with the command 'managit' or 'managit --start'"
	@echo "run 'managit --help' for help"