create-env:
	@git clone https://github.com/vgomes-p/managit.git ~/.managit
	@echo "managit enviroment created at ~/.managit, now you can finish creating the alias and then call it with the command 'managit'"
install:
	@git clone https://github.com/vgomes-p/managit.git ~/.managit
	@sudo pip install ~/.managit/program/. --break-system-packages
	@echo "managit installed at ~/.managit, now you can call it with the command 'managit' or 'managit --start'"
	@echo "run 'managit --help' for help"